"""Settings alanlari modele eklendi

Revision ID: 0733163ed4aa
Revises: 71e9b72e41f5
Create Date: 2026-02-21 11:30:55.775086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0733163ed4aa'
down_revision = '71e9b72e41f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme_preferences', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('layout_preference', sa.String(length=20), nullable=False, server_default='classic'))
        batch_op.add_column(sa.Column('notification_preferences', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('locale_preferences', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('show_page_guides', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('guide_character_style', sa.String(length=50), nullable=False, server_default='professional'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('guide_character_style')
        batch_op.drop_column('show_page_guides')
        batch_op.drop_column('locale_preferences')
        batch_op.drop_column('notification_preferences')
        batch_op.drop_column('layout_preference')
        batch_op.drop_column('theme_preferences')

    # ### end Alembic commands ###
