"""Supabase Full Kurulum

Revision ID: 2047a12f5ca2
Revises: 
Create Date: 2026-01-17 19:59:39.369272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2047a12f5ca2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kurum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kisa_ad', sa.String(length=100), nullable=False),
    sa.Column('ticari_unvan', sa.String(length=200), nullable=False),
    sa.Column('faaliyet_alani', sa.String(length=200), nullable=True),
    sa.Column('adres', sa.Text(), nullable=True),
    sa.Column('il', sa.String(length=100), nullable=True),
    sa.Column('ilce', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('web_adresi', sa.String(length=200), nullable=True),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('calisan_sayisi', sa.Integer(), nullable=True),
    sa.Column('sektor', sa.String(length=100), nullable=True),
    sa.Column('vergi_dairesi', sa.String(length=100), nullable=True),
    sa.Column('vergi_numarasi', sa.String(length=20), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('amac', sa.Text(), nullable=True),
    sa.Column('vizyon', sa.Text(), nullable=True),
    sa.Column('stratejik_profil', sa.Text(), nullable=True),
    sa.Column('stratejik_durum', sa.String(length=50), nullable=True),
    sa.Column('stratejik_son_guncelleme', sa.DateTime(), nullable=True),
    sa.Column('show_guide_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('silindi', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kurum', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kurum_kisa_ad'), ['kisa_ad'], unique=False)
        batch_op.create_index(batch_op.f('ix_kurum_silindi'), ['silindi'], unique=False)

    op.create_table('mock_competency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_competitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_crisismode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_daoproposal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_daovote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_deepworksession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_doomsdayscenario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_gamescenario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_gembawalk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_influencescore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_legacyknowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_marketintel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_metaversedepartment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_mudafinding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_objectivecomment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_orgchange',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_orgscenario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_persona',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_planitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_productsimulation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_safetycheck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_simulationscenario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_smartcontract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_strategicplan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_strategicrisk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_successionplan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_usercompetency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_wellbeingscore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_yearlychronicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('structure', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('task_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('sistem_rol', sa.String(length=50), nullable=False),
    sa.Column('surec_rol', sa.String(length=50), nullable=True),
    sa.Column('kurum_id', sa.Integer(), nullable=False),
    sa.Column('profile_photo', sa.String(length=500), nullable=True),
    sa.Column('theme_preferences', sa.Text(), nullable=True),
    sa.Column('layout_preference', sa.String(length=20), nullable=True),
    sa.Column('guide_character_style', sa.String(length=50), nullable=True),
    sa.Column('show_page_guides', sa.Boolean(), nullable=False),
    sa.Column('completed_walkthroughs', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('silindi', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['kurum_id'], ['kurum.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_kurum_id'), ['kurum_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_silindi'), ['silindi'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sistem_rol'), ['sistem_rol'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('yetki_matrisi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('yetki_kodu', sa.String(length=100), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('aciklama', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('yetki_matrisi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_yetki_matrisi_rol'), ['rol'], unique=False)

    op.create_table('ana_strateji',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kurum_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('ad', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kurum_id'], ['kurum.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kurum_id', 'code', name='uq_ana_strateji_kurum_code')
    )
    with op.batch_alter_table('ana_strateji', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ana_strateji_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_ana_strateji_kurum_id'), ['kurum_id'], unique=False)

    op.create_table('corporate_identity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kurum_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kurum_id'], ['kurum.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dashboard_layout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('layout_name', sa.String(length=100), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('layout_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dashboard_layout', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dashboard_layout_user_id'), ['user_id'], unique=False)

    op.create_table('deger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kurum_id', sa.Integer(), nullable=False),
    sa.Column('baslik', sa.String(length=200), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['kurum_id'], ['kurum.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('etik_kural',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kurum_id', sa.Integer(), nullable=False),
    sa.Column('baslik', sa.String(length=200), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['kurum_id'], ['kurum.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kalite_politikasi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kurum_id', sa.Integer(), nullable=False),
    sa.Column('baslik', sa.String(length=200), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['kurum_id'], ['kurum.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kullanici_yetki',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('yetki_kodu', sa.String(length=100), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('atayan_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['atayan_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kullanici_yetki', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kullanici_yetki_user_id'), ['user_id'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tip', sa.String(length=50), nullable=False),
    sa.Column('baslik', sa.String(length=200), nullable=False),
    sa.Column('mesaj', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('okundu', sa.Boolean(), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=True),
    sa.Column('surec_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('ilgili_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ilgili_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    op.create_table('ozel_yetki',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kullanici_id', sa.Integer(), nullable=False),
    sa.Column('yetki_kodu', sa.String(length=100), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('veren_kullanici_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kullanici_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['veren_kullanici_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ozel_yetki', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ozel_yetki_kullanici_id'), ['kullanici_id'], unique=False)

    op.create_table('pestle_analizi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kurum_id', sa.Integer(), nullable=False),
    sa.Column('kategori', sa.String(length=20), nullable=False),
    sa.Column('baslik', sa.String(length=200), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('etki', sa.String(length=20), nullable=True),
    sa.Column('oncelik', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kurum_id'], ['kurum.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pestle_analizi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pestle_analizi_kurum_id'), ['kurum_id'], unique=False)

    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kurum_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('health_score', sa.Integer(), nullable=True),
    sa.Column('health_status', sa.String(length=50), nullable=True),
    sa.Column('notification_settings', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kurum_id'], ['kurum.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_is_archived'), ['is_archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_kurum_id'), ['kurum_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_manager_id'), ['manager_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_start_date'), ['start_date'], unique=False)

    op.create_table('surec',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kurum_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('ad', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('dokuman_no', sa.String(length=50), nullable=True),
    sa.Column('rev_no', sa.String(length=20), nullable=True),
    sa.Column('rev_tarihi', sa.Date(), nullable=True),
    sa.Column('ilk_yayin_tarihi', sa.Date(), nullable=True),
    sa.Column('durum', sa.String(length=50), nullable=True),
    sa.Column('ilerleme', sa.Integer(), nullable=True),
    sa.Column('baslangic_siniri', sa.Text(), nullable=True),
    sa.Column('bitis_siniri', sa.Text(), nullable=True),
    sa.Column('baslangic_tarihi', sa.Date(), nullable=True),
    sa.Column('bitis_tarihi', sa.Date(), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('silindi', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['kurum_id'], ['kurum.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('surec', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_surec_ad'), ['ad'], unique=False)
        batch_op.create_index(batch_op.f('ix_surec_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_surec_kurum_id'), ['kurum_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_surec_silindi'), ['silindi'], unique=False)

    op.create_table('swot_analizi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kurum_id', sa.Integer(), nullable=False),
    sa.Column('kategori', sa.String(length=20), nullable=False),
    sa.Column('baslik', sa.String(length=200), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('oncelik', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kurum_id'], ['kurum.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('swot_analizi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_swot_analizi_kurum_id'), ['kurum_id'], unique=False)

    op.create_table('user_activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tip', sa.String(length=50), nullable=False),
    sa.Column('baslik', sa.String(length=200), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('surec_id', sa.Integer(), nullable=True),
    sa.Column('ilgili_user_id', sa.Integer(), nullable=True),
    sa.Column('bireysel_pg_id', sa.Integer(), nullable=True),
    sa.Column('surec_pg_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ilgili_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_activity_log_user_id'), ['user_id'], unique=False)

    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('project_name', sa.String(length=200), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alt_strateji',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ana_strateji_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('ad', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('target_method', sa.String(length=10), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ana_strateji_id'], ['ana_strateji.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alt_strateji', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alt_strateji_ana_strateji_id'), ['ana_strateji_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alt_strateji_code'), ['code'], unique=False)

    op.create_table('capacity_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('weekly_hours', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('capacity_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capacity_plan_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_capacity_plan_user_id'), ['user_id'], unique=False)

    op.create_table('integration_hook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('integration_hook', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_hook_project_id'), ['project_id'], unique=False)

    op.create_table('process_owners',
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['surec.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('process_id', 'user_id')
    )
    op.create_table('project_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_members',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.create_table('project_observers',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.create_table('project_related_processes',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('surec_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['surec_id'], ['surec.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'surec_id')
    )
    op.create_table('project_risk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('probability', sa.String(length=20), nullable=True),
    sa.Column('impact', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raid_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('probability', sa.Integer(), nullable=True),
    sa.Column('impact', sa.Integer(), nullable=True),
    sa.Column('mitigation_plan', sa.Text(), nullable=True),
    sa.Column('assumption_validation_date', sa.Date(), nullable=True),
    sa.Column('assumption_validated', sa.Boolean(), nullable=True),
    sa.Column('assumption_notes', sa.Text(), nullable=True),
    sa.Column('issue_urgency', sa.String(length=50), nullable=True),
    sa.Column('issue_affected_work', sa.String(length=200), nullable=True),
    sa.Column('dependency_task_id', sa.Integer(), nullable=True),
    sa.Column('dependency_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raid_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raid_item_project_id'), ['project_id'], unique=False)

    op.create_table('rule_definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('trigger', sa.String(length=100), nullable=False),
    sa.Column('condition_json', sa.Text(), nullable=True),
    sa.Column('actions_json', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule_definition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_definition_project_id'), ['project_id'], unique=False)

    op.create_table('sla',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('target_hours', sa.Integer(), nullable=False),
    sa.Column('breach_policy', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sla', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sla_project_id'), ['project_id'], unique=False)

    op.create_table('sprint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surec_faaliyet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surec_id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=200), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('baslangic_tarihi', sa.Date(), nullable=True),
    sa.Column('bitis_tarihi', sa.Date(), nullable=True),
    sa.Column('durum', sa.String(length=50), nullable=True),
    sa.Column('ilerleme', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['surec_id'], ['surec.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('surec_faaliyet', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_surec_faaliyet_surec_id'), ['surec_id'], unique=False)

    op.create_table('surec_liderleri',
    sa.Column('surec_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['surec_id'], ['surec.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('surec_id', 'user_id')
    )
    op.create_table('surec_uyeleri',
    sa.Column('surec_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['surec_id'], ['surec.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('surec_id', 'user_id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('external_assignee_name', sa.String(length=200), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('estimated_time', sa.Float(), nullable=True),
    sa.Column('actual_time', sa.Float(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('is_measurable', sa.Boolean(), nullable=True),
    sa.Column('planned_output_value', sa.Float(), nullable=True),
    sa.Column('related_indicator_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('reminder_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_project_id'), ['project_id'], unique=False)

    op.create_table('working_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_working', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('working_day', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_working_day_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_working_day_project_id'), ['project_id'], unique=False)

    op.create_table('bireysel_faaliyet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=200), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('baslangic_tarihi', sa.Date(), nullable=True),
    sa.Column('bitis_tarihi', sa.Date(), nullable=True),
    sa.Column('durum', sa.String(length=50), nullable=True),
    sa.Column('ilerleme', sa.Integer(), nullable=True),
    sa.Column('kaynak', sa.String(length=50), nullable=True),
    sa.Column('kaynak_surec_id', sa.Integer(), nullable=True),
    sa.Column('kaynak_surec_faaliyet_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kaynak_surec_faaliyet_id'], ['surec_faaliyet.id'], ),
    sa.ForeignKeyConstraint(['kaynak_surec_id'], ['surec.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bireysel_faaliyet', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bireysel_faaliyet_kaynak_surec_faaliyet_id'), ['kaynak_surec_faaliyet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bireysel_faaliyet_kaynak_surec_id'), ['kaynak_surec_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bireysel_faaliyet_user_id'), ['user_id'], unique=False)

    op.create_table('recurring_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('cron_expr', sa.String(length=100), nullable=False),
    sa.Column('template_task_id', sa.Integer(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['template_task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurring_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_task_project_id'), ['project_id'], unique=False)

    op.create_table('strategy_process_matrix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub_strategy_id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('relationship_strength', sa.Integer(), nullable=True),
    sa.Column('relationship_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['process_id'], ['surec.id'], ),
    sa.ForeignKeyConstraint(['sub_strategy_id'], ['alt_strateji.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sub_strategy_id', 'process_id', name='uq_strategy_process_matrix')
    )
    with op.batch_alter_table('strategy_process_matrix', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_process_matrix_process_id'), ['process_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_process_matrix_sub_strategy_id'), ['sub_strategy_id'], unique=False)

    op.create_table('surec_alt_stratejiler',
    sa.Column('surec_id', sa.Integer(), nullable=False),
    sa.Column('alt_strateji_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alt_strateji_id'], ['alt_strateji.id'], ),
    sa.ForeignKeyConstraint(['surec_id'], ['surec.id'], ),
    sa.PrimaryKeyConstraint('surec_id', 'alt_strateji_id')
    )
    op.create_table('surec_performans_gostergesi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surec_id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=200), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('kodu', sa.String(length=50), nullable=True),
    sa.Column('hedef_deger', sa.String(length=100), nullable=True),
    sa.Column('olcum_birimi', sa.String(length=50), nullable=True),
    sa.Column('periyot', sa.String(length=50), nullable=True),
    sa.Column('veri_alinacak_yer', sa.String(length=200), nullable=True),
    sa.Column('hedef_belirleme_yontemi', sa.String(length=200), nullable=True),
    sa.Column('veri_toplama_yontemi', sa.String(length=50), nullable=True),
    sa.Column('calculation_method', sa.String(length=20), nullable=True),
    sa.Column('agirlik', sa.Integer(), nullable=True),
    sa.Column('onemli', sa.Boolean(), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=True),
    sa.Column('gosterge_turu', sa.String(length=50), nullable=True),
    sa.Column('basari_puani', sa.Integer(), nullable=True),
    sa.Column('agirlikli_basari_puani', sa.Float(), nullable=True),
    sa.Column('basari_puani_araliklari', sa.Text(), nullable=True),
    sa.Column('onceki_yil_ortalamasi', sa.Float(), nullable=True),
    sa.Column('target_method', sa.String(length=10), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('alt_strateji_id', sa.Integer(), nullable=True),
    sa.Column('baslangic_tarihi', sa.Date(), nullable=True),
    sa.Column('bitis_tarihi', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alt_strateji_id'], ['alt_strateji.id'], ),
    sa.ForeignKeyConstraint(['surec_id'], ['surec.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('surec_performans_gostergesi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_surec_performans_gostergesi_alt_strateji_id'), ['alt_strateji_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_surec_performans_gostergesi_surec_id'), ['surec_id'], unique=False)

    op.create_table('task_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_baseline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('planned_start', sa.Date(), nullable=True),
    sa.Column('planned_end', sa.Date(), nullable=True),
    sa.Column('planned_effort', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_baseline', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_baseline_task_id'), ['task_id'], unique=False)

    op.create_table('task_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_dependency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('successor_id', sa.Integer(), nullable=False),
    sa.Column('predecessor_id', sa.Integer(), nullable=False),
    sa.Column('dependency_type', sa.String(length=4), nullable=True),
    sa.Column('lag_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['predecessor_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['successor_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_dependency', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_dependency_predecessor_id'), ['predecessor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_dependency_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_dependency_successor_id'), ['successor_id'], unique=False)

    op.create_table('task_impact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('impact_type', sa.String(length=50), nullable=True),
    sa.Column('impact_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_impact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_impact_task_id'), ['task_id'], unique=False)

    op.create_table('task_predecessors',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('predecessor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['predecessor_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'predecessor_id')
    )
    op.create_table('task_sprint',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('sprint_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprint.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'sprint_id')
    )
    op.create_table('task_subtask',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bireysel_performans_gostergesi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=200), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('kodu', sa.String(length=50), nullable=True),
    sa.Column('hedef_deger', sa.String(length=100), nullable=True),
    sa.Column('gerceklesen_deger', sa.String(length=100), nullable=True),
    sa.Column('olcum_birimi', sa.String(length=50), nullable=True),
    sa.Column('periyot', sa.String(length=50), nullable=True),
    sa.Column('agirlik', sa.Integer(), nullable=True),
    sa.Column('onemli', sa.Boolean(), nullable=True),
    sa.Column('baslangic_tarihi', sa.Date(), nullable=True),
    sa.Column('bitis_tarihi', sa.Date(), nullable=True),
    sa.Column('durum', sa.String(length=50), nullable=True),
    sa.Column('kaynak', sa.String(length=50), nullable=True),
    sa.Column('kaynak_surec_id', sa.Integer(), nullable=True),
    sa.Column('kaynak_surec_pg_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kaynak_surec_id'], ['surec.id'], ),
    sa.ForeignKeyConstraint(['kaynak_surec_pg_id'], ['surec_performans_gostergesi.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bireysel_performans_gostergesi', schema=None) as batch_op:
        batch_op.create_index('idx_bireysel_pg_user', ['user_id', 'kaynak'], unique=False)
        batch_op.create_index(batch_op.f('ix_bireysel_performans_gostergesi_ad'), ['ad'], unique=False)
        batch_op.create_index(batch_op.f('ix_bireysel_performans_gostergesi_kaynak_surec_id'), ['kaynak_surec_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bireysel_performans_gostergesi_kaynak_surec_pg_id'), ['kaynak_surec_pg_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bireysel_performans_gostergesi_user_id'), ['user_id'], unique=False)

    op.create_table('faaliyet_takip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bireysel_faaliyet_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('yil', sa.Integer(), nullable=False),
    sa.Column('ay', sa.Integer(), nullable=False),
    sa.Column('gerceklesti', sa.Boolean(), nullable=True),
    sa.Column('not_text', sa.Text(), nullable=True),
    sa.Column('tamamlanma_tarihi', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bireysel_faaliyet_id'], ['bireysel_faaliyet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favori_kpi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('surec_pg_id', sa.Integer(), nullable=False),
    sa.Column('sira', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['surec_pg_id'], ['surec_performans_gostergesi.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_mention',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('mentioned_user_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['task_comment.id'], ),
    sa.ForeignKeyConstraint(['mentioned_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performans_gosterge_veri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bireysel_pg_id', sa.Integer(), nullable=False),
    sa.Column('yil', sa.Integer(), nullable=False),
    sa.Column('veri_tarihi', sa.Date(), nullable=False),
    sa.Column('giris_periyot_tipi', sa.String(length=20), nullable=True),
    sa.Column('giris_periyot_no', sa.Integer(), nullable=True),
    sa.Column('giris_periyot_ay', sa.Integer(), nullable=True),
    sa.Column('ceyrek', sa.Integer(), nullable=True),
    sa.Column('ay', sa.Integer(), nullable=True),
    sa.Column('hafta', sa.Integer(), nullable=True),
    sa.Column('gun', sa.Integer(), nullable=True),
    sa.Column('hedef_deger', sa.String(length=100), nullable=True),
    sa.Column('gerceklesen_deger', sa.String(length=100), nullable=False),
    sa.Column('durum', sa.String(length=50), nullable=True),
    sa.Column('durum_yuzdesi', sa.Float(), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bireysel_pg_id'], ['bireysel_performans_gostergesi.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('performans_gosterge_veri', schema=None) as batch_op:
        batch_op.create_index('idx_pg_veri_lookup', ['bireysel_pg_id', 'yil', 'veri_tarihi'], unique=False)
        batch_op.create_index('idx_pg_veri_user', ['user_id', 'yil'], unique=False)
        batch_op.create_index(batch_op.f('ix_performans_gosterge_veri_bireysel_pg_id'), ['bireysel_pg_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_performans_gosterge_veri_veri_tarihi'), ['veri_tarihi'], unique=False)
        batch_op.create_index(batch_op.f('ix_performans_gosterge_veri_yil'), ['yil'], unique=False)

    op.create_table('performans_gosterge_veri_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pg_veri_id', sa.Integer(), nullable=False),
    sa.Column('islem_tipi', sa.String(length=20), nullable=False),
    sa.Column('eski_deger', sa.Text(), nullable=True),
    sa.Column('yeni_deger', sa.Text(), nullable=True),
    sa.Column('degisiklik_aciklama', sa.Text(), nullable=True),
    sa.Column('islem_yapan_user_id', sa.Integer(), nullable=False),
    sa.Column('islem_tarihi', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['islem_yapan_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['pg_veri_id'], ['performans_gosterge_veri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('performans_gosterge_veri_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_performans_gosterge_veri_audit_pg_veri_id'), ['pg_veri_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performans_gosterge_veri_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_performans_gosterge_veri_audit_pg_veri_id'))

    op.drop_table('performans_gosterge_veri_audit')
    with op.batch_alter_table('performans_gosterge_veri', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_performans_gosterge_veri_yil'))
        batch_op.drop_index(batch_op.f('ix_performans_gosterge_veri_veri_tarihi'))
        batch_op.drop_index(batch_op.f('ix_performans_gosterge_veri_bireysel_pg_id'))
        batch_op.drop_index('idx_pg_veri_user')
        batch_op.drop_index('idx_pg_veri_lookup')

    op.drop_table('performans_gosterge_veri')
    op.drop_table('task_mention')
    op.drop_table('favori_kpi')
    op.drop_table('faaliyet_takip')
    with op.batch_alter_table('bireysel_performans_gostergesi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bireysel_performans_gostergesi_user_id'))
        batch_op.drop_index(batch_op.f('ix_bireysel_performans_gostergesi_kaynak_surec_pg_id'))
        batch_op.drop_index(batch_op.f('ix_bireysel_performans_gostergesi_kaynak_surec_id'))
        batch_op.drop_index(batch_op.f('ix_bireysel_performans_gostergesi_ad'))
        batch_op.drop_index('idx_bireysel_pg_user')

    op.drop_table('bireysel_performans_gostergesi')
    op.drop_table('time_entry')
    op.drop_table('task_subtask')
    op.drop_table('task_sprint')
    op.drop_table('task_predecessors')
    with op.batch_alter_table('task_impact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_impact_task_id'))

    op.drop_table('task_impact')
    with op.batch_alter_table('task_dependency', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_dependency_successor_id'))
        batch_op.drop_index(batch_op.f('ix_task_dependency_project_id'))
        batch_op.drop_index(batch_op.f('ix_task_dependency_predecessor_id'))

    op.drop_table('task_dependency')
    op.drop_table('task_comment')
    with op.batch_alter_table('task_baseline', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_baseline_task_id'))

    op.drop_table('task_baseline')
    op.drop_table('task_activity')
    with op.batch_alter_table('surec_performans_gostergesi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_surec_performans_gostergesi_surec_id'))
        batch_op.drop_index(batch_op.f('ix_surec_performans_gostergesi_alt_strateji_id'))

    op.drop_table('surec_performans_gostergesi')
    op.drop_table('surec_alt_stratejiler')
    with op.batch_alter_table('strategy_process_matrix', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_process_matrix_sub_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_strategy_process_matrix_process_id'))

    op.drop_table('strategy_process_matrix')
    with op.batch_alter_table('recurring_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_task_project_id'))

    op.drop_table('recurring_task')
    with op.batch_alter_table('bireysel_faaliyet', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bireysel_faaliyet_user_id'))
        batch_op.drop_index(batch_op.f('ix_bireysel_faaliyet_kaynak_surec_id'))
        batch_op.drop_index(batch_op.f('ix_bireysel_faaliyet_kaynak_surec_faaliyet_id'))

    op.drop_table('bireysel_faaliyet')
    with op.batch_alter_table('working_day', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_working_day_project_id'))
        batch_op.drop_index(batch_op.f('ix_working_day_date'))

    op.drop_table('working_day')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_project_id'))
        batch_op.drop_index(batch_op.f('ix_task_parent_id'))

    op.drop_table('task')
    op.drop_table('surec_uyeleri')
    op.drop_table('surec_liderleri')
    with op.batch_alter_table('surec_faaliyet', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_surec_faaliyet_surec_id'))

    op.drop_table('surec_faaliyet')
    op.drop_table('sprint')
    with op.batch_alter_table('sla', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sla_project_id'))

    op.drop_table('sla')
    with op.batch_alter_table('rule_definition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_definition_project_id'))

    op.drop_table('rule_definition')
    with op.batch_alter_table('raid_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raid_item_project_id'))

    op.drop_table('raid_item')
    op.drop_table('project_risk')
    op.drop_table('project_related_processes')
    op.drop_table('project_observers')
    op.drop_table('project_members')
    op.drop_table('project_file')
    op.drop_table('process_owners')
    with op.batch_alter_table('integration_hook', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_hook_project_id'))

    op.drop_table('integration_hook')
    with op.batch_alter_table('capacity_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capacity_plan_user_id'))
        batch_op.drop_index(batch_op.f('ix_capacity_plan_project_id'))

    op.drop_table('capacity_plan')
    with op.batch_alter_table('alt_strateji', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alt_strateji_code'))
        batch_op.drop_index(batch_op.f('ix_alt_strateji_ana_strateji_id'))

    op.drop_table('alt_strateji')
    op.drop_table('activity')
    with op.batch_alter_table('user_activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_activity_log_user_id'))

    op.drop_table('user_activity_log')
    with op.batch_alter_table('swot_analizi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_swot_analizi_kurum_id'))

    op.drop_table('swot_analizi')
    with op.batch_alter_table('surec', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_surec_silindi'))
        batch_op.drop_index(batch_op.f('ix_surec_kurum_id'))
        batch_op.drop_index(batch_op.f('ix_surec_code'))
        batch_op.drop_index(batch_op.f('ix_surec_ad'))

    op.drop_table('surec')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_start_date'))
        batch_op.drop_index(batch_op.f('ix_project_name'))
        batch_op.drop_index(batch_op.f('ix_project_manager_id'))
        batch_op.drop_index(batch_op.f('ix_project_kurum_id'))
        batch_op.drop_index(batch_op.f('ix_project_is_archived'))
        batch_op.drop_index(batch_op.f('ix_project_end_date'))

    op.drop_table('project')
    with op.batch_alter_table('pestle_analizi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pestle_analizi_kurum_id'))

    op.drop_table('pestle_analizi')
    with op.batch_alter_table('ozel_yetki', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ozel_yetki_kullanici_id'))

    op.drop_table('ozel_yetki')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))

    op.drop_table('notification')
    with op.batch_alter_table('kullanici_yetki', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kullanici_yetki_user_id'))

    op.drop_table('kullanici_yetki')
    op.drop_table('kalite_politikasi')
    op.drop_table('etik_kural')
    op.drop_table('deger')
    with op.batch_alter_table('dashboard_layout', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dashboard_layout_user_id'))

    op.drop_table('dashboard_layout')
    op.drop_table('corporate_identity')
    with op.batch_alter_table('ana_strateji', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ana_strateji_kurum_id'))
        batch_op.drop_index(batch_op.f('ix_ana_strateji_code'))

    op.drop_table('ana_strateji')
    with op.batch_alter_table('yetki_matrisi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_yetki_matrisi_rol'))

    op.drop_table('yetki_matrisi')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_sistem_rol'))
        batch_op.drop_index(batch_op.f('ix_user_silindi'))
        batch_op.drop_index(batch_op.f('ix_user_kurum_id'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('task_template')
    op.drop_table('tag')
    op.drop_table('project_template')
    op.drop_table('mock_yearlychronicle')
    op.drop_table('mock_wellbeingscore')
    op.drop_table('mock_usercompetency')
    op.drop_table('mock_successionplan')
    op.drop_table('mock_strategicrisk')
    op.drop_table('mock_strategicplan')
    op.drop_table('mock_smartcontract')
    op.drop_table('mock_simulationscenario')
    op.drop_table('mock_safetycheck')
    op.drop_table('mock_productsimulation')
    op.drop_table('mock_planitem')
    op.drop_table('mock_persona')
    op.drop_table('mock_orgscenario')
    op.drop_table('mock_orgchange')
    op.drop_table('mock_objectivecomment')
    op.drop_table('mock_mudafinding')
    op.drop_table('mock_metaversedepartment')
    op.drop_table('mock_marketintel')
    op.drop_table('mock_legacyknowledge')
    op.drop_table('mock_influencescore')
    op.drop_table('mock_gembawalk')
    op.drop_table('mock_gamescenario')
    op.drop_table('mock_doomsdayscenario')
    op.drop_table('mock_deepworksession')
    op.drop_table('mock_daovote')
    op.drop_table('mock_daoproposal')
    op.drop_table('mock_crisismode')
    op.drop_table('mock_competitor')
    op.drop_table('mock_competency')
    with op.batch_alter_table('kurum', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kurum_silindi'))
        batch_op.drop_index(batch_op.f('ix_kurum_kisa_ad'))

    op.drop_table('kurum')
    # ### end Alembic commands ###
