"""module_component_slugs bileÅŸen=BileÅŸen Ä°smi

Revision ID: 2b72be414b31
Revises: 8b84b6081087
Create Date: 2026-02-21 14:58:27.121959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b72be414b31'
down_revision = '8b84b6081087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_component_slugs',
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('component_slug', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['system_modules.id'], ),
    sa.PrimaryKeyConstraint('module_id', 'component_slug')
    )
    op.drop_table('module_components')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_components',
    sa.Column('module_id', sa.INTEGER(), nullable=False),
    sa.Column('component_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['system_components.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['system_modules.id'], ),
    sa.PrimaryKeyConstraint('module_id', 'component_id')
    )
    op.drop_table('module_component_slugs')
    # ### end Alembic commands ###
