"""Add process models

Revision ID: 461675c755b0
Revises: 87e9b1dcd08d
Create Date: 2026-02-22 02:40:24.155236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '461675c755b0'
down_revision = '87e9b1dcd08d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('english_name', sa.String(length=200), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('document_no', sa.String(length=50), nullable=True),
    sa.Column('revision_no', sa.String(length=20), nullable=True),
    sa.Column('revision_date', sa.Date(), nullable=True),
    sa.Column('first_publish_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('start_boundary', sa.Text(), nullable=True),
    sa.Column('end_boundary', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['processes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processes_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_processes_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_processes_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_processes_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processes_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('process_kpis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('target_value', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('period', sa.String(length=50), nullable=True),
    sa.Column('data_source', sa.String(length=200), nullable=True),
    sa.Column('target_setting_method', sa.String(length=200), nullable=True),
    sa.Column('data_collection_method', sa.String(length=50), nullable=True),
    sa.Column('calculation_method', sa.String(length=20), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('is_important', sa.Boolean(), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=True),
    sa.Column('calculated_score', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sub_strategy_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_strategy_id'], ['sub_strategies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('process_kpis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_process_kpis_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_process_kpis_process_id'), ['process_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_process_kpis_sub_strategy_id'), ['sub_strategy_id'], unique=False)

    op.create_table('process_leaders',
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('process_id', 'user_id')
    )
    op.create_table('process_members',
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('process_id', 'user_id')
    )
    op.create_table('process_owners_table',
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('process_id', 'user_id')
    )
    op.create_table('process_sub_strategies',
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('sub_strategy_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_strategy_id'], ['sub_strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('process_id', 'sub_strategy_id')
    )
    op.create_table('kpi_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_kpi_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('data_date', sa.Date(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=True),
    sa.Column('period_no', sa.Integer(), nullable=True),
    sa.Column('period_month', sa.Integer(), nullable=True),
    sa.Column('target_value', sa.String(length=100), nullable=True),
    sa.Column('actual_value', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('status_percentage', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['process_kpi_id'], ['process_kpis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kpi_data', schema=None) as batch_op:
        batch_op.create_index('idx_kpi_data_lookup', ['process_kpi_id', 'year', 'data_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_kpi_data_data_date'), ['data_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_kpi_data_process_kpi_id'), ['process_kpi_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kpi_data_year'), ['year'], unique=False)

    op.create_table('process_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('process_kpi_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['process_kpi_id'], ['process_kpis.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('process_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_process_activities_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_process_activities_process_id'), ['process_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_process_activities_process_kpi_id'), ['process_kpi_id'], unique=False)

    op.create_table('kpi_data_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kpi_data_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('action_detail', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kpi_data_id'], ['kpi_data.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kpi_data_audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kpi_data_audits_kpi_data_id'), ['kpi_data_id'], unique=False)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_roles_slug'), type_='unique')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.VARCHAR(length=64), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_roles_slug'), ['slug'])

    with op.batch_alter_table('kpi_data_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kpi_data_audits_kpi_data_id'))

    op.drop_table('kpi_data_audits')
    with op.batch_alter_table('process_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_process_activities_process_kpi_id'))
        batch_op.drop_index(batch_op.f('ix_process_activities_process_id'))
        batch_op.drop_index(batch_op.f('ix_process_activities_is_active'))

    op.drop_table('process_activities')
    with op.batch_alter_table('kpi_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kpi_data_year'))
        batch_op.drop_index(batch_op.f('ix_kpi_data_process_kpi_id'))
        batch_op.drop_index(batch_op.f('ix_kpi_data_data_date'))
        batch_op.drop_index('idx_kpi_data_lookup')

    op.drop_table('kpi_data')
    op.drop_table('process_sub_strategies')
    op.drop_table('process_owners_table')
    op.drop_table('process_members')
    op.drop_table('process_leaders')
    with op.batch_alter_table('process_kpis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_process_kpis_sub_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_process_kpis_process_id'))
        batch_op.drop_index(batch_op.f('ix_process_kpis_is_active'))

    op.drop_table('process_kpis')
    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processes_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_processes_parent_id'))
        batch_op.drop_index(batch_op.f('ix_processes_name'))
        batch_op.drop_index(batch_op.f('ix_processes_is_active'))
        batch_op.drop_index(batch_op.f('ix_processes_code'))

    op.drop_table('processes')
    # ### end Alembic commands ###
