"""RouteRegistry modeli eklendi

Revision ID: 8b84b6081087
Revises: 0733163ed4aa
Create Date: 2026-02-21 11:58:26.200102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b84b6081087'
down_revision = '0733163ed4aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('url_rule', sa.String(length=512), nullable=False),
    sa.Column('methods', sa.String(length=128), nullable=True),
    sa.Column('component_slug', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route_registry')
    # ### end Alembic commands ###
