"""Tenant modeli eski form alanlariyla genisletildi

Revision ID: d6c4380baeb5
Revises: 42b12497afce
Create Date: 2026-02-21 00:39:48.270627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c4380baeb5'
down_revision = '42b12497afce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_area', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('sector', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('employee_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contact_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('website_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('tax_office', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tax_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('max_user_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('license_end_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('license_end_date')
        batch_op.drop_column('max_user_count')
        batch_op.drop_column('tax_number')
        batch_op.drop_column('tax_office')
        batch_op.drop_column('website_url')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('contact_email')
        batch_op.drop_column('employee_count')
        batch_op.drop_column('sector')
        batch_op.drop_column('activity_area')

    # ### end Alembic commands ###
