"""add_pg_extra_fields_activity_track

Revision ID: d94e7cc6f534
Revises: 461675c755b0
Create Date: 2026-02-22 12:34:02.620295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd94e7cc6f534'
down_revision = '461675c755b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['process_activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'year', 'month', name='uq_activity_track')
    )
    with op.batch_alter_table('activity_tracks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_tracks_activity_id'), ['activity_id'], unique=False)

    with op.batch_alter_table('process_kpis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gosterge_turu', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('target_method', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('basari_puani_araliklari', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('onceki_yil_ortalamasi', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_kpis', schema=None) as batch_op:
        batch_op.drop_column('onceki_yil_ortalamasi')
        batch_op.drop_column('basari_puani_araliklari')
        batch_op.drop_column('target_method')
        batch_op.drop_column('gosterge_turu')

    with op.batch_alter_table('activity_tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_tracks_activity_id'))

    op.drop_table('activity_tracks')
    # ### end Alembic commands ###
