"""Add individual PG activity kpi data audit track favorite models

Revision ID: f7920a9ab0db
Revises: d94e7cc6f534
Create Date: 2026-02-22 19:16:27.449938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7920a9ab0db'
down_revision = 'd94e7cc6f534'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_kpis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('process_kpi_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['process_kpi_id'], ['process_kpis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'process_kpi_id', name='uq_favorite_kpi')
    )
    with op.batch_alter_table('favorite_kpis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorite_kpis_process_kpi_id'), ['process_kpi_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favorite_kpis_user_id'), ['user_id'], unique=False)

    op.create_table('individual_performance_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('target_value', sa.String(length=100), nullable=True),
    sa.Column('actual_value', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('period', sa.String(length=50), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('is_important', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_process_id', sa.Integer(), nullable=True),
    sa.Column('source_process_kpi_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=True),
    sa.Column('basari_puani_araliklari', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_process_id'], ['processes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_process_kpi_id'], ['process_kpis.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('individual_performance_indicators', schema=None) as batch_op:
        batch_op.create_index('idx_indiv_pg_user_source', ['user_id', 'source'], unique=False)
        batch_op.create_index(batch_op.f('ix_individual_performance_indicators_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_individual_performance_indicators_source_process_id'), ['source_process_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_individual_performance_indicators_source_process_kpi_id'), ['source_process_kpi_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_individual_performance_indicators_user_id'), ['user_id'], unique=False)

    op.create_table('individual_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_process_id', sa.Integer(), nullable=True),
    sa.Column('source_process_activity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_process_activity_id'], ['process_activities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_process_id'], ['processes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('individual_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_individual_activities_source_process_activity_id'), ['source_process_activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_individual_activities_source_process_id'), ['source_process_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_individual_activities_user_id'), ['user_id'], unique=False)

    op.create_table('individual_kpi_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('individual_pg_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('data_date', sa.Date(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=True),
    sa.Column('period_no', sa.Integer(), nullable=True),
    sa.Column('period_month', sa.Integer(), nullable=True),
    sa.Column('target_value', sa.String(length=100), nullable=True),
    sa.Column('actual_value', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('status_percentage', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['individual_pg_id'], ['individual_performance_indicators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('individual_kpi_data', schema=None) as batch_op:
        batch_op.create_index('idx_indiv_kpi_data_lookup', ['individual_pg_id', 'year', 'data_date'], unique=False)
        batch_op.create_index('idx_indiv_kpi_data_user', ['user_id', 'year'], unique=False)
        batch_op.create_index(batch_op.f('ix_individual_kpi_data_data_date'), ['data_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_individual_kpi_data_individual_pg_id'), ['individual_pg_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_individual_kpi_data_year'), ['year'], unique=False)

    op.create_table('individual_activity_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('individual_activity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['individual_activity_id'], ['individual_activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('individual_activity_id', 'year', 'month', name='uq_indiv_activity_track')
    )
    with op.batch_alter_table('individual_activity_tracks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_individual_activity_tracks_individual_activity_id'), ['individual_activity_id'], unique=False)

    op.create_table('individual_kpi_data_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('individual_kpi_data_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('action_detail', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['individual_kpi_data_id'], ['individual_kpi_data.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('individual_kpi_data_audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_individual_kpi_data_audits_individual_kpi_data_id'), ['individual_kpi_data_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('individual_kpi_data_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_individual_kpi_data_audits_individual_kpi_data_id'))

    op.drop_table('individual_kpi_data_audits')
    with op.batch_alter_table('individual_activity_tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_individual_activity_tracks_individual_activity_id'))

    op.drop_table('individual_activity_tracks')
    with op.batch_alter_table('individual_kpi_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_individual_kpi_data_year'))
        batch_op.drop_index(batch_op.f('ix_individual_kpi_data_individual_pg_id'))
        batch_op.drop_index(batch_op.f('ix_individual_kpi_data_data_date'))
        batch_op.drop_index('idx_indiv_kpi_data_user')
        batch_op.drop_index('idx_indiv_kpi_data_lookup')

    op.drop_table('individual_kpi_data')
    with op.batch_alter_table('individual_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_individual_activities_user_id'))
        batch_op.drop_index(batch_op.f('ix_individual_activities_source_process_id'))
        batch_op.drop_index(batch_op.f('ix_individual_activities_source_process_activity_id'))

    op.drop_table('individual_activities')
    with op.batch_alter_table('individual_performance_indicators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_individual_performance_indicators_user_id'))
        batch_op.drop_index(batch_op.f('ix_individual_performance_indicators_source_process_kpi_id'))
        batch_op.drop_index(batch_op.f('ix_individual_performance_indicators_source_process_id'))
        batch_op.drop_index(batch_op.f('ix_individual_performance_indicators_name'))
        batch_op.drop_index('idx_indiv_pg_user_source')

    op.drop_table('individual_performance_indicators')
    with op.batch_alter_table('favorite_kpis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorite_kpis_user_id'))
        batch_op.drop_index(batch_op.f('ix_favorite_kpis_process_kpi_id'))

    op.drop_table('favorite_kpis')
    # ### end Alembic commands ###
