# -*- coding: utf-8 -*-
"""Diğer legacy modeller — Activity, audit, faz placeholder'ları."""
from models import (  # noqa: F401
    Activity,
    AuditLog,
    Feedback,
    UserDashboardSettings,
    ObjectiveComment,
    StrategicPlan,
    PlanItem,
    GembaWalk,
    Competency,
    UserCompetency,
    StrategicRisk,
    MudaFinding,
    CrisisMode,
    SafetyCheck,
    SuccessionPlan,
    OrgScenario,
    OrgChange,
    InfluenceScore,
    MarketIntel,
    WellbeingScore,
    SimulationScenario,
    DeepWorkSession,
    Persona,
    ProductSimulation,
    SmartContract,
    DaoProposal,
    DaoVote,
    MetaverseDepartment,
    LegacyKnowledge,
    Competitor,
    GameScenario,
    DoomsdayScenario,
    YearlyChronicle,
    CorporateIdentity,
)
