# -*- coding: utf-8 -*-
"""Geriye dönük uyumluluk — proje modelleri app.models.portfolio_project altında."""
from app.models.portfolio_project import (  # noqa: F401
    Project,
    Task,
    TaskImpact,
    TaskComment,
    TaskMention,
    ProjectFile,
    ProjectRisk,
    Tag,
    TaskSubtask,
    TimeEntry,
    TaskActivity,
    ProjectTemplate,
    TaskTemplate,
    Sprint,
    TaskSprint,
    TaskDependency,
    IntegrationHook,
    RuleDefinition,
    SLA,
    RecurringTask,
    WorkingDay,
    CapacityPlan,
    RaidItem,
    TaskBaseline,
    project_members,
    project_observers,
    project_leaders,
    project_related_processes,
    task_predecessors,
)
